require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CityHallsController do

  # This should return the minimal set of attributes required to create a valid
  # CityHall. As you add validations to CityHall, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CityHallsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all city_halls as @city_halls" do
      city_hall = CityHall.create! valid_attributes
      get :index, {}, valid_session
      assigns(:city_halls).should eq([city_hall])
    end
  end

  describe "GET show" do
    it "assigns the requested city_hall as @city_hall" do
      city_hall = CityHall.create! valid_attributes
      get :show, {:id => city_hall.to_param}, valid_session
      assigns(:city_hall).should eq(city_hall)
    end
  end

  describe "GET new" do
    it "assigns a new city_hall as @city_hall" do
      get :new, {}, valid_session
      assigns(:city_hall).should be_a_new(CityHall)
    end
  end

  describe "GET edit" do
    it "assigns the requested city_hall as @city_hall" do
      city_hall = CityHall.create! valid_attributes
      get :edit, {:id => city_hall.to_param}, valid_session
      assigns(:city_hall).should eq(city_hall)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CityHall" do
        expect {
          post :create, {:city_hall => valid_attributes}, valid_session
        }.to change(CityHall, :count).by(1)
      end

      it "assigns a newly created city_hall as @city_hall" do
        post :create, {:city_hall => valid_attributes}, valid_session
        assigns(:city_hall).should be_a(CityHall)
        assigns(:city_hall).should be_persisted
      end

      it "redirects to the created city_hall" do
        post :create, {:city_hall => valid_attributes}, valid_session
        response.should redirect_to(CityHall.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved city_hall as @city_hall" do
        # Trigger the behavior that occurs when invalid params are submitted
        CityHall.any_instance.stub(:save).and_return(false)
        post :create, {:city_hall => { "name" => "invalid value" }}, valid_session
        assigns(:city_hall).should be_a_new(CityHall)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CityHall.any_instance.stub(:save).and_return(false)
        post :create, {:city_hall => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested city_hall" do
        city_hall = CityHall.create! valid_attributes
        # Assuming there are no other city_halls in the database, this
        # specifies that the CityHall created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CityHall.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => city_hall.to_param, :city_hall => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested city_hall as @city_hall" do
        city_hall = CityHall.create! valid_attributes
        put :update, {:id => city_hall.to_param, :city_hall => valid_attributes}, valid_session
        assigns(:city_hall).should eq(city_hall)
      end

      it "redirects to the city_hall" do
        city_hall = CityHall.create! valid_attributes
        put :update, {:id => city_hall.to_param, :city_hall => valid_attributes}, valid_session
        response.should redirect_to(city_hall)
      end
    end

    describe "with invalid params" do
      it "assigns the city_hall as @city_hall" do
        city_hall = CityHall.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CityHall.any_instance.stub(:save).and_return(false)
        put :update, {:id => city_hall.to_param, :city_hall => { "name" => "invalid value" }}, valid_session
        assigns(:city_hall).should eq(city_hall)
      end

      it "re-renders the 'edit' template" do
        city_hall = CityHall.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CityHall.any_instance.stub(:save).and_return(false)
        put :update, {:id => city_hall.to_param, :city_hall => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested city_hall" do
      city_hall = CityHall.create! valid_attributes
      expect {
        delete :destroy, {:id => city_hall.to_param}, valid_session
      }.to change(CityHall, :count).by(-1)
    end

    it "redirects to the city_halls list" do
      city_hall = CityHall.create! valid_attributes
      delete :destroy, {:id => city_hall.to_param}, valid_session
      response.should redirect_to(city_halls_url)
    end
  end

end
