require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MailingSchedulesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # MailingSchedule. As you add validations to MailingSchedule, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MailingSchedulesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mailing_schedules as @mailing_schedules" do
      mailing_schedule = MailingSchedule.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:mailing_schedules)).to eq([mailing_schedule])
    end
  end

  describe "GET show" do
    it "assigns the requested mailing_schedule as @mailing_schedule" do
      mailing_schedule = MailingSchedule.create! valid_attributes
      get :show, {:id => mailing_schedule.to_param}, valid_session
      expect(assigns(:mailing_schedule)).to eq(mailing_schedule)
    end
  end

  describe "GET new" do
    it "assigns a new mailing_schedule as @mailing_schedule" do
      get :new, {}, valid_session
      expect(assigns(:mailing_schedule)).to be_a_new(MailingSchedule)
    end
  end

  describe "GET edit" do
    it "assigns the requested mailing_schedule as @mailing_schedule" do
      mailing_schedule = MailingSchedule.create! valid_attributes
      get :edit, {:id => mailing_schedule.to_param}, valid_session
      expect(assigns(:mailing_schedule)).to eq(mailing_schedule)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MailingSchedule" do
        expect {
          post :create, {:mailing_schedule => valid_attributes}, valid_session
        }.to change(MailingSchedule, :count).by(1)
      end

      it "assigns a newly created mailing_schedule as @mailing_schedule" do
        post :create, {:mailing_schedule => valid_attributes}, valid_session
        expect(assigns(:mailing_schedule)).to be_a(MailingSchedule)
        expect(assigns(:mailing_schedule)).to be_persisted
      end

      it "redirects to the created mailing_schedule" do
        post :create, {:mailing_schedule => valid_attributes}, valid_session
        expect(response).to redirect_to(MailingSchedule.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mailing_schedule as @mailing_schedule" do
        post :create, {:mailing_schedule => invalid_attributes}, valid_session
        expect(assigns(:mailing_schedule)).to be_a_new(MailingSchedule)
      end

      it "re-renders the 'new' template" do
        post :create, {:mailing_schedule => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested mailing_schedule" do
        mailing_schedule = MailingSchedule.create! valid_attributes
        put :update, {:id => mailing_schedule.to_param, :mailing_schedule => new_attributes}, valid_session
        mailing_schedule.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested mailing_schedule as @mailing_schedule" do
        mailing_schedule = MailingSchedule.create! valid_attributes
        put :update, {:id => mailing_schedule.to_param, :mailing_schedule => valid_attributes}, valid_session
        expect(assigns(:mailing_schedule)).to eq(mailing_schedule)
      end

      it "redirects to the mailing_schedule" do
        mailing_schedule = MailingSchedule.create! valid_attributes
        put :update, {:id => mailing_schedule.to_param, :mailing_schedule => valid_attributes}, valid_session
        expect(response).to redirect_to(mailing_schedule)
      end
    end

    describe "with invalid params" do
      it "assigns the mailing_schedule as @mailing_schedule" do
        mailing_schedule = MailingSchedule.create! valid_attributes
        put :update, {:id => mailing_schedule.to_param, :mailing_schedule => invalid_attributes}, valid_session
        expect(assigns(:mailing_schedule)).to eq(mailing_schedule)
      end

      it "re-renders the 'edit' template" do
        mailing_schedule = MailingSchedule.create! valid_attributes
        put :update, {:id => mailing_schedule.to_param, :mailing_schedule => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mailing_schedule" do
      mailing_schedule = MailingSchedule.create! valid_attributes
      expect {
        delete :destroy, {:id => mailing_schedule.to_param}, valid_session
      }.to change(MailingSchedule, :count).by(-1)
    end

    it "redirects to the mailing_schedules list" do
      mailing_schedule = MailingSchedule.create! valid_attributes
      delete :destroy, {:id => mailing_schedule.to_param}, valid_session
      expect(response).to redirect_to(mailing_schedules_url)
    end
  end

end
